# Generated by Django 4.0.2 on 2023-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtdcomment',
            name='media',
            field=models.FileField(blank=True, help_text='Link to media. <code>File</code>', null=True, upload_to=''),
        ),
    ]
